# Pull gems from RubyGems
source 'https://rubygems.org'

gem 'sass',               ">= 3.2.1" 
gem 'compass',            ">= 0.12.2" 
gem 'color-schemer',      ">= 0.2.1" 
gem 'toolkit',            ">= 0.2.3" 
gem 'modular-scale', 	  ">=1.0.6"