# If you have OpenSSL installed, we recommend updating
# the following line to use "https"
source 'http://rubygems.org'

gem "middleman", "~>3.2.2"

# Live-reloading plugin
gem "middleman-livereload", "~> 3.1.0"

# Sass stuff

gem 'compass', '~> 1.0.0.alpha.19'
gem 'sass', '~> 3.3.5'
gem 'toolkit', '~> 2.3.0'
gem 'color-schemer', '~> 0.2.8'
gem 'modular-scale', '~> 2.0.5'