# If you have OpenSSL installed, we recommend updating
# the following line to use "https"
source 'http://rubygems.org'

gem "middleman", "~> 3.1.5"
gem "middleman-blog", "~> 3.3.0"
gem "nokogiri"

# For feed.xml.builder
gem "builder", "~> 3.0"

gem 'color-schemer',      ">= 0.2.1" 
gem 'toolkit',            ">= 0.2.3" 
gem 'modular-scale', 	  ">=1.0.6"
